const alphabetBrailleCells = [
  { name: "⠁", braille_name: "Cell A", translation: "A", braille_id: "1" },
  { name: "⠃", braille_name: "Cell B", translation: "B", braille_id: "2" },
  { name: "⠉", braille_name: "Cell C", translation: "C", braille_id: "3" },
  { name: "⠙", braille_name: "Cell D", translation: "D", braille_id: "4" },
  { name: "⠑", braille_name: "Cell E", translation: "E", braille_id: "5" },
  { name: "⠋", braille_name: "Cell F", translation: "F", braille_id: "6" },
  { name: "⠛", braille_name: "Cell G", translation: "G", braille_id: "7" },
  { name: "⠓", braille_name: "Cell H", translation: "H", braille_id: "8" },
  { name: "⠊", braille_name: "Cell I", translation: "I", braille_id: "9" },
  { name: "⠚", braille_name: "Cell J", translation: "J", braille_id: "10" },
  { name: "⠅", braille_name: "Cell K", translation: "K", braille_id: "11" },
  { name: "⠇", braille_name: "Cell L", translation: "L", braille_id: "12" },
  { name: "⠍", braille_name: "Cell M", translation: "M", braille_id: "13" },
  { name: "⠝", braille_name: "Cell N", translation: "N", braille_id: "14" },
  { name: "⠕", braille_name: "Cell O", translation: "O", braille_id: "15" },
  { name: "⠏", braille_name: "Cell P", translation: "P", braille_id: "16" },
  { name: "⠟", braille_name: "Cell Q", translation: "Q", braille_id: "17" },
  { name: "⠗", braille_name: "Cell R", translation: "R", braille_id: "18" },
  { name: "⠎", braille_name: "Cell S", translation: "S", braille_id: "19" },
  { name: "⠞", braille_name: "Cell T", translation: "T", braille_id: "20" },
  { name: "⠥", braille_name: "Cell U", translation: "U", braille_id: "21" },
  { name: "⠧", braille_name: "Cell V", translation: "V", braille_id: "22" },
  { name: "⠺", braille_name: "Cell W", translation: "W", braille_id: "23" },
  { name: "⠭", braille_name: "Cell X", translation: "X", braille_id: "24" },
  { name: "⠽", braille_name: "Cell Y", translation: "Y", braille_id: "25" },
  { name: "⠵", braille_name: "Cell Z", translation: "Z", braille_id: "26" },
];

const popularWords = [
  {
    word: "⠓⠑⠇⠇⠕. ",
    translation: "hello",
    word_id: "1",
  },
  {
    word: "⠑⠁⠞. ",
    translation: "eat",
    word_id: "2",
  },
  {
    word: "⠎⠇⠑⠑⠏. ",
    translation: "sleep",
    word_id: "3",
  },
  {
    word: "⠃⠁⠞⠓. ",
    translation: "bath",
    word_id: "4",
  },
  {
    word: "⠺⠁⠇⠅. ",
    translation: "walk",
    word_id: "5",
  },
  {
    word: "⠇⠑⠁⠗⠝. ",
    translation: "learn",
    word_id: "6",
  },
  {
    word: "⠺⠗⠊⠞⠑. ",
    translation: "write",
    word_id: "7",
  },
  {
    word: "⠗⠑⠁⠙. ",
    translation: "read",
    word_id: "8",
  },
];

const numberBrailleCells = [
  { name: "⠼⠁", braille_name: "Cell 1", translation: "1", braille_id: "1" },
  { name: "⠼⠃", braille_name: "Cell 2", translation: "2", braille_id: "2" },
  { name: "⠼⠉", braille_name: "Cell 3", translation: "3", braille_id: "3" },
  { name: "⠼⠙", braille_name: "Cell 4", translation: "4", braille_id: "4" },
  { name: "⠼⠑", braille_name: "Cell 5", translation: "5", braille_id: "5" },
  { name: "⠼⠋", braille_name: "Cell 6", translation: "6", braille_id: "6" },
  { name: "⠼⠛", braille_name: "Cell 7", translation: "7", braille_id: "7" },
  { name: "⠼⠓", braille_name: "Cell 8", translation: "8", braille_id: "8" },
  { name: "⠼⠊", braille_name: "Cell 9", translation: "9", braille_id: "9" },
  { name: "⠼⠚", braille_name: "Cell 10", translation: "10", braille_id: "10" },
  { name: "⠼⠅", braille_name: "Cell 11", translation: "11", braille_id: "11" },
  { name: "⠼⠇", braille_name: "Cell 12", translation: "12", braille_id: "12" },
  { name: "⠼⠍", braille_name: "Cell 13", translation: "13", braille_id: "13" },
  { name: "⠼⠝", braille_name: "Cell 14", translation: "14", braille_id: "14" },
  { name: "⠼⠕", braille_name: "Cell 15", translation: "15", braille_id: "15" },
  { name: "⠼⠏", braille_name: "Cell 16", translation: "16", braille_id: "16" },
  { name: "⠼⠟", braille_name: "Cell 17", translation: "17", braille_id: "17" },
  { name: "⠼⠗", braille_name: "Cell 18", translation: "18", braille_id: "18" },
  { name: "⠼⠎", braille_name: "Cell 19", translation: "19", braille_id: "19" },
  { name: "⠼⠞", braille_name: "Cell 20", translation: "20", braille_id: "20" },
];

export { alphabetBrailleCells, popularWords, numberBrailleCells };
